<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_quotaName</name>
   <tag></tag>
   <elementGuidId>a4be3fbd-ac2f-4748-83fc-09e5b7ac0b0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1437</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1437']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70a7a5c0-b010-4bac-a12a-81af7e5b6f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>fbd17078-30cd-492f-bef6-d5754d6b17c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dcf78705-4877-4584-a1e8-79f247277267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1437</value>
      <webElementGuid>7b604e64-3084-49dd-ae2b-43abaf7c8d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e3b7527-9896-468a-8ab4-3a549c09af9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-1437</value>
      <webElementGuid>7fe8ca93-0982-46be-aa2b-d0dd81c00507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quotaName</value>
      <webElementGuid>225e86e2-831a-4b50-9b6d-d4f1c4c4faa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1437&quot;)</value>
      <webElementGuid>e4b37ec1-5cd0-4c56-a4ba-128e7f31dc3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1437']</value>
      <webElementGuid>734a86fa-f923-4b1f-b195-99040ce8cdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[3]/c-qr-h-o-details/div/div/div/lightning-input/div/div/input</value>
      <webElementGuid>e403b3ec-91a1-49b8-9bd3-7597f540a463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/lightning-input/div/div/input</value>
      <webElementGuid>46bdcef3-8451-4d46-aae1-41b50e403488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1437' and @name = 'quotaName']</value>
      <webElementGuid>33717fbf-c6d0-4486-94d9-cdaf367af91d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
