<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit nav items_SearchTree</name>
   <tag></tag>
   <elementGuidId>91cee1ec-3dbf-4761-8cdf-660e0d7109c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-71</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-71']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bfeea0e-7c69-4e58-99db-c39edc0d65b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>58d1c723-2995-4675-aa78-8da15bce1025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>38e51e9b-f24d-40bf-9be7-7f87b529ebf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-71</value>
      <webElementGuid>2f0ccce4-39c1-419b-b03d-dd21d3594e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6f9780f-00d5-4626-9f87-c12c17064def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-71</value>
      <webElementGuid>f5845245-9b7f-4f16-ad29-ac2aba804f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>24bbfcfc-d4e9-44ba-b176-35f3bb6216e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchTree</value>
      <webElementGuid>b0e8e250-4079-4d81-b124-fee08a003ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-71&quot;)</value>
      <webElementGuid>86511090-8f60-4b5d-9c0f-1a8292722f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-71']</value>
      <webElementGuid>14f8d90c-a515-4ae8-a421-b6d184f52f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/div/div/span/lightning-input/div/div/input</value>
      <webElementGuid>351459db-b741-448d-99ed-24bd1eb2fdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input/div/div/input</value>
      <webElementGuid>de2535dc-4644-489b-833b-1387898d99ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-71' and @placeholder = 'Search' and @name = 'SearchTree']</value>
      <webElementGuid>9360f321-944d-44da-a5cc-cc5c41f427b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
