<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Super Admin Integration_roster-group</name>
   <tag></tag>
   <elementGuidId>3c7ab253-755d-472f-adbc-d6cf7e24dc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a1D5e0000007l6iEAA-1435</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='a1D5e0000007l6iEAA-1435']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ef4798b-2165-4fe5-8f39-55bf0c3f5193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roster-radio</value>
      <webElementGuid>1245138c-e4f8-4948-a29d-7215ffb2e69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>35eb4158-a440-43b0-84ad-a20bcf1e07d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1D5e0000007l6iEAA-1435</value>
      <webElementGuid>41f4116b-dc4e-4d38-83ed-bea64fa033ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roster-group</value>
      <webElementGuid>c2095fe4-290e-4f81-b341-3b304dec3374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>63d439d2-1ebb-441f-b933-31764597a5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1D5e0000007l6iEAA-1435&quot;)</value>
      <webElementGuid>05de7678-bd54-469e-82a9-0e1697da46a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1D5e0000007l6iEAA-1435']</value>
      <webElementGuid>7b002cdc-bf63-41dd-8630-5195f679c2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-2-1435']/div[2]/table/tbody/tr[27]/td/input</value>
      <webElementGuid>72e50f97-7bfb-42bd-849a-508bb616b74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td/input</value>
      <webElementGuid>a83cde52-411c-439c-bd2c-da30ae00bf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'a1D5e0000007l6iEAA-1435' and @name = 'roster-group']</value>
      <webElementGuid>4ba0c156-407e-41d8-bee7-e8337836df99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
