<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vinod Bendre_goal-group</name>
   <tag></tag>
   <elementGuidId>385bf598-e52b-4def-b2c8-0679690e7fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.DM-Goal_Table.slds-table.slds-table_cell-buffer.slds-table_bordered.slds-table_col-bordered > tbody > tr.slds-hint-parent > td > #a3T5e000000n5U5EAI-1435</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='a3T5e000000n5U5EAI-1435'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>926cc0a7-5426-42ff-a14f-911c0d28299a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goal-radio-data-adapter</value>
      <webElementGuid>f6e5b955-694f-4002-b22c-be2bf27d4a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1f193ac5-48d3-4f28-964e-00cbe45aab5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a3T5e000000n5U5EAI-1435</value>
      <webElementGuid>8e5c8a19-d599-4846-9fd2-64724f96c432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goal-group</value>
      <webElementGuid>f67089ed-06d7-42bd-9cc3-71b51ab3b551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>db10598a-077b-4db1-ac8c-6ec830707ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-id-1-1435&quot;)/div[3]/table[@class=&quot;DM-Goal_Table slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent&quot;]/td[1]/input[@id=&quot;a3T5e000000n5U5EAI-1435&quot;]</value>
      <webElementGuid>4ba4e995-c848-4dbc-b4d2-900715f5e736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='a3T5e000000n5U5EAI-1435'])[2]</value>
      <webElementGuid>d2abb7e4-f2f5-4d02-81d4-ab01fe661977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1-1435']/div[3]/table/tbody/tr[10]/td/input</value>
      <webElementGuid>59066266-20b0-4c83-a9d2-146e850a8f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[10]/td/input</value>
      <webElementGuid>e2ec029e-0f41-4f4d-8832-3534e5b2288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'a3T5e000000n5U5EAI-1435' and @name = 'goal-group']</value>
      <webElementGuid>7599ded2-f445-4f75-8812-6bc2b49384ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
