<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-spinner_View Refinement_loader-ba_ef34d4</name>
   <tag></tag>
   <elementGuidId>73acb8f4-3ce6-4bbb-95a8-87b157fb11e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-spinner.loader-background.slds-spinner_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[3]/c-qr-h-o-details/div/lightning-spinner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-spinner</value>
      <webElementGuid>3753198d-e96e-4571-80d0-f60b49f53c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader-background slds-spinner_container</value>
      <webElementGuid>436af2ae-52b7-40e4-bf40-703919af5830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>ecdb6bd0-b246-401c-a6ce-4f89800c0dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>c75bbc63-8165-4c1e-a25f-f51be30a346c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-1&quot;]/c-qr-h-o-details[1]/div[1]/lightning-spinner[@class=&quot;loader-background slds-spinner_container&quot;]</value>
      <webElementGuid>ddd45f58-fe56-4825-9b1f-1b526d9953fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[3]/c-qr-h-o-details/div/lightning-spinner</value>
      <webElementGuid>bb52e129-8804-4adf-aa78-983467dc47e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Refinement'])[1]/following::lightning-spinner[1]</value>
      <webElementGuid>e1eec318-e586-40f4-9b9e-73c7d693a4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Level Configurations'])[1]/following::lightning-spinner[1]</value>
      <webElementGuid>936da14c-acac-4927-a052-a344ec61cedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::lightning-spinner[1]</value>
      <webElementGuid>57a7e69e-3d4e-4a4a-8492-9c91017c3ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::lightning-spinner[1]</value>
      <webElementGuid>144a15f1-74d8-43c6-9400-6282ea2c7db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-spinner</value>
      <webElementGuid>decddf68-c99b-4855-9001-7b6fe86524f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
