<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_phTest_slds-checkbox_faux</name>
   <tag></tag>
   <elementGuidId>46eb9961-091e-4580-97d8-9d61beb7a30a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.slds-checkbox_faux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[4]/c-qr-h-o-cycle-level/div/div/table/tbody/tr/td[4]/div/div[2]/lightning-input/div/span/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>080072d0-364b-47f7-9c9f-ad2aba5a4fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>indicator</value>
      <webElementGuid>381c036f-4c98-476d-8172-15fcd3aacd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-checkbox_faux</value>
      <webElementGuid>0ca2eab5-2772-4e9e-b88d-65937dc6023a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-2&quot;]/c-qr-h-o-cycle-level[1]/div[1]/div[1]/table[@class=&quot;slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered&quot;]/tbody[1]/tr[1]/td[4]/div[@class=&quot;slds-p-around_xx-small&quot;]/div[2]/lightning-input[@class=&quot;ApplyToAllNotes slds-form-element&quot;]/div[@class=&quot;slds-form-element__control slds-grow&quot;]/span[@class=&quot;slds-checkbox&quot;]/label[@class=&quot;slds-checkbox__label&quot;]/span[@class=&quot;slds-checkbox_faux&quot;]</value>
      <webElementGuid>46449aad-ceb8-410c-8f4a-57b3db0f29f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[4]/c-qr-h-o-cycle-level/div/div/table/tbody/tr/td[4]/div/div[2]/lightning-input/div/span/label/span</value>
      <webElementGuid>adf90eb7-edd1-46c1-b00d-41c76f7a0e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>368d1f46-c175-4a5a-afa9-0f428431d28a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
