<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>8b48e2c2-4af3-49dc-b2b2-570709431f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#All-1435 > span.slds-media__body > span.slds-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='All-1435']/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8d0acef-25a0-4467-85c5-6531ca2a544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>4414507b-02e2-4915-8a20-52b28b0c88ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>44c02b26-a111-4320-aefc-00008d0605d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>373228df-020c-437f-9d2f-c366f3c618f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;All-1435&quot;)/span[@class=&quot;slds-media__body&quot;]/span[@class=&quot;slds-truncate&quot;]</value>
      <webElementGuid>6b019e83-2ca4-4219-8640-593efe072b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='All-1435']/span[2]/span</value>
      <webElementGuid>ecd1fa87-6bd0-4006-9fb3-d04aebe54321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[1]/following::span[5]</value>
      <webElementGuid>a6701b26-bcf7-4493-9cf4-07aa8a1d92c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::span[6]</value>
      <webElementGuid>21905818-aba6-487e-bad4-c0d912735aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRIDION'])[1]/preceding::span[3]</value>
      <webElementGuid>74c6b5f0-8560-4bdf-abb8-7350cc697801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESMERON'])[1]/preceding::span[7]</value>
      <webElementGuid>7e883e89-ebe2-4cbb-b015-f654997c3d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]/span</value>
      <webElementGuid>cd0c5f89-791a-4721-ba2c-278dab934529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'All' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>67a6cfff-636f-4b97-9a1c-8a744e420d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
