<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Alpha</name>
   <tag></tag>
   <elementGuidId>9b64c454-e291-4f9d-953b-1e8a976222ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-1443-0-1443 > span.slds-media__body > span.slds-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-1443-0-1443']/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>92cb8552-a4eb-437b-8935-3919e92a5864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>ad22cf29-976a-4d96-a247-b927e06e726a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alpha</value>
      <webElementGuid>01e7096e-41b4-4d20-a84a-3f3b3b86bb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alpha</value>
      <webElementGuid>a8fbe29e-1550-4dfd-b04a-ee5310cc293d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-1443-0-1443&quot;)/span[@class=&quot;slds-media__body&quot;]/span[@class=&quot;slds-truncate&quot;]</value>
      <webElementGuid>c2f73dc9-9386-4b7b-8f21-c24f68fe02fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-1443-0-1443']/span[2]/span</value>
      <webElementGuid>55a961c0-4439-4920-9112-0132c87468ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[1]/following::span[4]</value>
      <webElementGuid>434c76e3-a58d-4626-bb1e-1282df63dc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[2]/following::span[5]</value>
      <webElementGuid>97a7af2f-ffb1-449e-85b6-a5d441f5e7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Team'])[1]/preceding::span[1]</value>
      <webElementGuid>953fe1f7-5f9d-47d8-9310-83c49fd91ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Team'])[2]/preceding::span[1]</value>
      <webElementGuid>e0c06a07-afd0-47a8-a55d-3793c37e1397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alpha']/parent::*</value>
      <webElementGuid>be8ca566-b6b4-4d33-81e8-66dfc90ab261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/lightning-combobox/div/lightning-base-combobox/div/div[2]/lightning-base-combobox-item/span[2]/span</value>
      <webElementGuid>b4f796ba-5017-4bf0-b39a-1e7bab3b3644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Alpha' and (text() = 'Alpha' or . = 'Alpha')]</value>
      <webElementGuid>6b595f79-039a-4e4b-bd48-7e935b2796e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
