<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_phT</name>
   <tag></tag>
   <elementGuidId>a4822917-ab0c-4de0-bec2-2cd194f63650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.slds-textarea.refinementNotes.commentArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@value='phT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>034ae727-ac3b-4b0d-b860-2a775434d9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea refinementNotes commentArea</value>
      <webElementGuid>46a02c91-0bf0-4ae1-8edd-cd68adc18dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Level 2</value>
      <webElementGuid>c3fe771d-efa7-4501-9171-6ce1c352df13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d226a869-772e-4599-b40f-b66987741da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>phT</value>
      <webElementGuid>a1874276-cba7-4995-929a-4e012123f04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>phT</value>
      <webElementGuid>66354bf3-06eb-4b91-9c4e-7638bb40c088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-2&quot;]/c-qr-h-o-cycle-level[1]/div[1]/div[1]/table[@class=&quot;slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered&quot;]/tbody[1]/tr[1]/td[4]/div[@class=&quot;slds-p-around_xx-small&quot;]/textarea[@class=&quot;slds-textarea refinementNotes commentArea&quot;]</value>
      <webElementGuid>29a83f34-8cc6-4228-99c1-9fbf00836ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@value='phT']</value>
      <webElementGuid>8d3fdbfc-091f-4d6d-9b14-f895fb180429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[4]/c-qr-h-o-cycle-level/div/div/table/tbody/tr/td[4]/div/textarea</value>
      <webElementGuid>253b722a-af41-4829-814f-02368dfb440d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date for'])[2]/following::textarea[1]</value>
      <webElementGuid>d5f77742-c1ab-4dcd-88b3-bc2051f3273e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date after Jun 30, 2023'])[2]/following::textarea[1]</value>
      <webElementGuid>77746848-b31d-48d0-8628-72aa1ee6b8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply to all'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d5b468d9-0dc9-4a21-ac4b-f7e0abbd4b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAC District Manager'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b1dc699e-a8c4-4a51-9cde-a4c71e6d6450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='phT']/parent::*</value>
      <webElementGuid>2e2cd21e-6e7d-42cc-85a9-ea816885fdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0c3facf4-b584-4e2f-b939-03245fe0751e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'phT' or . = 'phT')]</value>
      <webElementGuid>27fe01fd-3c53-459b-80f8-5348c2dfb01c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
