<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_phTe</name>
   <tag></tag>
   <elementGuidId>3653ed5a-785a-46d5-ac6b-361246c579b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.slds-textarea.refinementNotes.commentArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@value='phTe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4372afd3-8d07-49e0-854b-0e12d84482d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea refinementNotes commentArea</value>
      <webElementGuid>43fcdcc4-3795-464f-a9c9-dbbf1acda90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Level 2</value>
      <webElementGuid>e77627a3-afa7-4cab-ac7a-811881759730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>22b24933-022c-4fc3-9c6c-ac632a13caac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>phTe</value>
      <webElementGuid>7b1d39f5-ffac-4393-9ddf-44805aac4111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>phTe</value>
      <webElementGuid>8ea85316-d6f1-48f9-9eb7-8e5531a716da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-2&quot;]/c-qr-h-o-cycle-level[1]/div[1]/div[1]/table[@class=&quot;slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered&quot;]/tbody[1]/tr[1]/td[4]/div[@class=&quot;slds-p-around_xx-small&quot;]/textarea[@class=&quot;slds-textarea refinementNotes commentArea&quot;]</value>
      <webElementGuid>0b875db3-27a1-413f-a525-192f75fc25f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@value='phTe']</value>
      <webElementGuid>287e2c31-e354-46b3-b8df-adc39528a54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[4]/c-qr-h-o-cycle-level/div/div/table/tbody/tr/td[4]/div/textarea</value>
      <webElementGuid>3ef96ca2-2e4e-4a58-b143-1949175524f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date for'])[2]/following::textarea[1]</value>
      <webElementGuid>835d46d3-e8e7-4a44-8296-82a823454cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date after Jun 30, 2023'])[2]/following::textarea[1]</value>
      <webElementGuid>c4f9f3e2-c191-47ef-a73a-f0b3f6f4ea34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply to all'])[1]/preceding::textarea[1]</value>
      <webElementGuid>90d426cc-a15a-4146-b4b7-63f10361a916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAC District Manager'])[1]/preceding::textarea[1]</value>
      <webElementGuid>82f93f54-a69a-4b92-8140-c8e21602e78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='phTe']/parent::*</value>
      <webElementGuid>e8ef77e3-4922-446a-bbdd-22b741317b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b55acc11-26fe-4b0d-bcb3-70599cf89018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'phTe' or . = 'phTe')]</value>
      <webElementGuid>3941fd2e-2a32-49a2-bff2-9a3bf72c84cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
