<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_rememberUn</name>
   <tag></tag>
   <elementGuidId>58eb8d9c-3e52-41a5-bebe-8af7083f7b12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberUn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberUn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ee75355-7adc-401d-98f3-3b48fd3388ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2309f908-9ddb-4ae4-ac41-0df398a8fd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r4 fl mr8</value>
      <webElementGuid>647b2c34-c858-42aa-a16e-738091d8349f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberUn</value>
      <webElementGuid>c43fed47-2a71-4cb0-973d-1304bc09f9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberUn</value>
      <webElementGuid>487de858-9451-41e0-959e-36199d97df31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberUn&quot;)</value>
      <webElementGuid>b61a2b6a-5ba0-4c34-94ae-57d4ec2977e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberUn']</value>
      <webElementGuid>2d28016c-6587-45ce-bfda-54d78f36a3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[3]/input</value>
      <webElementGuid>65911b9a-cd3a-41bd-b64c-0bfceb5b398a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d5a1df5b-c2be-49b9-8ba2-629033ac65c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'rememberUn' and @name = 'rememberUn']</value>
      <webElementGuid>d989e7a9-ba2b-422d-9bcb-93cefd437dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
